"""Initial migration

Revision ID: 0f4aa645289e
Revises: 
Create Date: 2026-06-17 08:02:55.296798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f4aa645289e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('shipping_method', sa.String(length=50), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=False),
    sa.Column('product_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('product_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_reviews_product_id'))
        batch_op.drop_index(batch_op.f('idx_reviews_rating'))

    op.drop_table('product_reviews')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_categories_parent_id'))
        batch_op.drop_index(batch_op.f('idx_categories_slug'))
        batch_op.drop_constraint(batch_op.f('categories_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['parent_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.alter_column('gallery_images',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.alter_column('meta_keywords',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.drop_index(batch_op.f('idx_products_attributes'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_products_average_rating'))
        batch_op.drop_index(batch_op.f('idx_products_category_id'))
        batch_op.drop_index(batch_op.f('idx_products_category_price'))
        batch_op.drop_index(batch_op.f('idx_products_category_status'))
        batch_op.drop_index(batch_op.f('idx_products_created_at'))
        batch_op.drop_index(batch_op.f('idx_products_is_best_seller'), postgresql_where='(is_best_seller = true)')
        batch_op.drop_index(batch_op.f('idx_products_is_featured'), postgresql_where='(is_featured = true)')
        batch_op.drop_index(batch_op.f('idx_products_is_new_arrival'), postgresql_where='(is_new_arrival = true)')
        batch_op.drop_index(batch_op.f('idx_products_is_on_sale'), postgresql_where='(is_on_sale = true)')
        batch_op.drop_index(batch_op.f('idx_products_low_stock'), postgresql_where='(quantity_in_stock <= low_stock_threshold)')
        batch_op.drop_index(batch_op.f('idx_products_name'))
        batch_op.drop_index(batch_op.f('idx_products_price'))
        batch_op.drop_index(batch_op.f('idx_products_price_range'), postgresql_where='(is_active = true)')
        batch_op.drop_index(batch_op.f('idx_products_published_at'))
        batch_op.drop_index(batch_op.f('idx_products_quantity_in_stock'))
        batch_op.drop_index(batch_op.f('idx_products_sku'))
        batch_op.drop_index(batch_op.f('idx_products_slug'))
        batch_op.drop_index(batch_op.f('idx_products_specifications'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_products_status'))
        batch_op.drop_index(batch_op.f('idx_products_status_price'))
        batch_op.drop_index(batch_op.f('idx_products_subcategory_id'))
        batch_op.drop_index(batch_op.f('idx_products_tags'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_products_total_reviews'))
        batch_op.drop_column('rating_count_4')
        batch_op.drop_column('rating_count_3')
        batch_op.drop_column('rating_count_2')
        batch_op.drop_column('rating_count_1')
        batch_op.drop_column('rating_count_5')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_count_5', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rating_count_1', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rating_count_2', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rating_count_3', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rating_count_4', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_products_total_reviews'), [sa.literal_column('total_reviews DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_products_tags'), ['tags'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_products_subcategory_id'), ['subcategory_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_status_price'), ['status', 'price'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_specifications'), ['specifications'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_products_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_quantity_in_stock'), ['quantity_in_stock'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_price_range'), ['price'], unique=False, postgresql_where='(is_active = true)')
        batch_op.create_index(batch_op.f('idx_products_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_low_stock'), ['quantity_in_stock'], unique=False, postgresql_where='(quantity_in_stock <= low_stock_threshold)')
        batch_op.create_index(batch_op.f('idx_products_is_on_sale'), ['is_on_sale'], unique=False, postgresql_where='(is_on_sale = true)')
        batch_op.create_index(batch_op.f('idx_products_is_new_arrival'), ['is_new_arrival'], unique=False, postgresql_where='(is_new_arrival = true)')
        batch_op.create_index(batch_op.f('idx_products_is_featured'), ['is_featured'], unique=False, postgresql_where='(is_featured = true)')
        batch_op.create_index(batch_op.f('idx_products_is_best_seller'), ['is_best_seller'], unique=False, postgresql_where='(is_best_seller = true)')
        batch_op.create_index(batch_op.f('idx_products_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_category_status'), ['category_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_category_price'), ['category_id', 'price'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_average_rating'), [sa.literal_column('average_rating DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_products_attributes'), ['attributes'], unique=False, postgresql_using='gin')
        batch_op.alter_column('meta_keywords',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.alter_column('gallery_images',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.alter_column('tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('categories_parent_id_fkey'), 'categories', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_categories_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_categories_parent_id'), ['parent_id'], unique=False)

    op.create_table('product_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('review', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_verified_purchase', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('product_reviews_rating_check')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_reviews_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('product_reviews_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_reviews_pkey'))
    )
    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_reviews_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('idx_reviews_product_id'), ['product_id'], unique=False)

    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
